baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Food Trailer Manufacturer and Supplier in New Zealand'
canonifyURLs = true
relativeURLs = true

[pagination]
paginate = 5


[outputs]
home = ["HTML", "RSS"]

[outputFormats]
  [outputFormats.RSS]
    mediaType = "application/rss+xml"
    baseName = "rss"
    isPlainText = false
    notAlternative = true